// <auto-generated />
namespace WebFramework.Persistence.Migrations.Products
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductsInitializeSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductsInitializeSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201604210816532_Products Initialize Schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
